version: '3.9'
services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: unionexplain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: ['redis-server', '--save', "", '--appendonly', 'no']
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data:
